### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by srcejon** [arodland/prop#42]
Hi,

I access current MUF and FOF2 geojson data via the URLs https://prop.kc2g.com/renders/current/mufd-normal-now.geojson and https://prop.kc2g.com/renders/current/fof2-normal-now.geojson

Is there any way to access historical data?

Thanks.

**Comment by arodland** [comment]
Yes, there's historical data available, but the details depend on exactly what you need and how old it is. Please email kc2g@kc2g.com with some specifics and I'll be happy to help you out
