### ISSUE TITLE
MUF/foF2 contour data in machine readable format

### ISSUE THREAD

**Issue by srcejon** [arodland/prop#9]
Hi,

Great project. I was wondering if you would consider making the muf / foF2 contour data used for the images on https://prop.kc2g.com/ available in a machine readable format, so it can be read and displayed by other applications?

The contours could perhaps be exported in GeoJSON https://en.wikipedia.org/wiki/GeoJSON - https://geojson.org/ or similar.

Thanks.

**Comment by arodland** [comment]
In fact it's already there: https://prop.kc2g.com/renders/current/mufd-normal-now.geojson (just take a map URL and replace svg with geojson). I'm not sure how usable it is though, it's very old code.

The data is also available in HDF5 format, not as contours, but as the MUF/foF2 values on a 1°x1° grid, which is what the contours are drawn from.

**Comment by srcejon** [comment]
Excellent, I'll give it a try. Thanks.

**Comment by srcejon** [comment]
Seems to work nicely. I've added support for MUF & foF2 contours and the station data to SDRangel's 3D Map:

![image](https://user-images.githubusercontent.com/57259258/180045243-dc1fa780-804f-481c-be77-ef60ea2f6a40.png)
